namespace Atlas.AI.Structured;

/// <summary>
/// Represents a strucured response generated by an Atlas Language model.
/// </summary>
public sealed record AtlasStructuredLanguageModelResponse(
    string Content);
